version: '3'
services:
  api:
    image: rubeha/shub_class
    environment:
      - DB_PASSWORD=shubclass@2023
      - DB_HOST=db
      - DB_DBNAME=ShubClass
      - DB_USERNAME=root
      - PORT=3000
      - JWT_KEY=shubclass@2023
      - MAIL_DISPLAY_NAME='Shub Classroom'
      - MAIL_USER=minishop.pbl3@gmail.com
      - MAIL_PASSWORD=yimcdficrfejnvfd
      - SERVER=localhost:3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
    ports:
      - 80:3000
    restart: always
  db:
    image: mysql:5.7.41
    environment:
      - MYSQL_ROOT_PASSWORD=shubclass@2023
    ports:
      - 33306:3306
    volumes:
      - ./docker-database:/var/lib/mysql
  redis:
    image: redis:7.0.5-alpine
    ports:
      - 6379:6379